### ISSUE TITLE
Stylecop project path

### ISSUE THREAD

**Issue by AlexsJones** [rfennell/StyleCopCmdLine#2]
Hi, 
I've locally had to unload and alter the StyleCop DLL references as you are using a relative path.

Might be an idea putting those in an AppConfig or hardcoding them to default on C:\Program Files (x86)\StyleCop 4.7

Cheers

**Comment by rfennell** [comment]
Good point, just committed a version of the wrapper project with the hint path in the .csproj set to the default location 
This is in 2efe18214c4ce43c0af6e2d2ec3b15822b9675c4
