### ISSUE TITLE
Could not load file or assembly StyleCop,

### ISSUE THREAD

**Issue by SonizciTR** [rfennell/StyleCopCmdLine#4]
Hi;

I run your code successfully at my TFS. Everything is perfect.

I changed your code a little in my dll (Not in your wrapper dll). I uploaded to TFS. Run the task at agent. Powershell invokes dll without problem. Code's "StyleCopConsole" declaration line, it throws  
"Could not load file or assembly 'StyleCop, Version=4.7.1000.0...."  Exception.  

We are using the same SytleCop dlls.

Have you ever got the same error? How did you solved it?

 _System.Management.Automation.MethodInvocationException: Exception calling "Scan" with "0" argument(s): "Could not load file or assembly 'StyleCop, Version=4.7.1000.0, Culture=neutral, PublicKeyToken=f904653c63bc2738' or one of its dependencies. The system cannot find the file specified." ---> System.IO.FileNotFoundException: Could not load file or assembly 'StyleCop, Version=4.7.1000.0, Culture=neutral, PublicKeyToken=f904653c63bc2738' or one of its dependencies. The system cannot find the file specified.
   at StyleCopWrapper.Wrapper.Scan()
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)_

**Comment by rfennell** [comment]
First point, there is a [VSTS extension](https://marketplace.visualstudio.com/items?itemName=richardfennellBM.BM-VSTS-StyleCop-Task) that wrappers all this code, I assume you have seen this.

The usual issues here I find is that there is a mismatch between the StyleCop.DLL (down to the minor version) installed on the build agent and wrappered by the script. 

I assume you mean it works as a script, you mean on the same VM as the build agent? Is a different version on this VM?

**Comment by SonizciTR** [comment]
First of all thank you for your code and help here.

Our TFS server at remote machine. Build agent is at my local machine.

I installed your extension, and run it successfully. There is no "Could not load file or assembly" exception.

I am %100 percent sure, they are "StyleCop, Version=4.7.1000.0". 2 of my colleague checked too.

Like your powershell code, i invoke my own dll's method. I compile my dll with the same Stylecop dlls that found in your code. I copied all the dlls from your code. We are using the same dlls.  

From my powershell code; If i trigger MyWrapper dll's Scan method first, then my dll's method, both code runs too. 

I edit registery to get more debug info and found this detail below. Agent is not looking the my dll's directory. All the StyleCop dlls are there. I am setting right folder with "Set-Location" powershell command and with a line at task.json file ("workingDirectory": "$(currentDirectory)"). I even check with "Get-Location" powerhshell command, and it is actually set the right location. But this debug info shows in runtime stil looks other places???

__LOG: DisplayName = StyleCop, Version=4.7.1000.0, Culture=neutral, PublicKeyToken=f904653c63bc2738
 (Fully-specified)
LOG: Appbase = file:///C:/tfs2015srv/agent/agent/worker/
LOG: Initial PrivatePath = NULL

# Calling assembly : (Unknown).

LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\tfs2015srv\agent\agent\worker\vsoWorker.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: StyleCop, Version=4.7.1000.0, Culture=neutral, PublicKeyToken=f904653c63bc2738
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/StyleCop/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/StyleCop/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Internal/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Internal/StyleCop/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Common/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Common/StyleCop/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs/StyleCop/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DTA/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DTA/StyleCop/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Plugins/Release/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Plugins/Release/StyleCop/StyleCop.DLL.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/StyleCop/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/StyleCop/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Internal/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Internal/StyleCop/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Common/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.Common/StyleCop/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DevTestLabs/StyleCop/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DTA/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Modules/Microsoft.TeamFoundation.DistributedTask.Task.DTA/StyleCop/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Plugins/Release/StyleCop.EXE.
LOG: Attempting download of new URL file:///C:/tfs2015srv/agent/agent/worker/Plugins/Release/StyleCop/StyleCop.EXE.__

**Comment by rfennell** [comment]
Strange, I am assuming that your StyleCop.dll is not in any of the folder listed above.

What happens if you place it in one of them?

Usually I would expect the file to be picked up because it is in the same folder as the PowerShell script.
Once think I do remember is you need the Rules base library too to get anything to work. Could that be an issue?

But it does just sound like the stylecop.dll is not in an expected location, sorry at this point I can't be any more help

**Comment by SonizciTR** [comment]
If I place StyleCop dlls one of those folder, everything works fine. I do not want to do that. There is a lot of other dlls there. If i try to copy my dlls, there will be version mayhem and write problem.

I uploaded my task with all my dlls in it. Result is same: "Could not load file or assembly" exception.

What do you mean about "Rules base library" ? I added "Microsoft.CSharp", "StyleCop", "StyleCop.Csharp", "StyleCop.Csharp.Rules" dlss to my class library. Same StyleCop dlls you use.

Yesterday we try to trace the problem with FusionLogViewer. At logs; when I run my dll, we see "Calling assembly : (Unknown)". But when we run your dll, "Calling assembly" shows your dll perfectly. We are now investigating this.

My project is at this link [TFS Sharp Task Runner](https://github.com/SonizciTR/TFSSharpTR)

**Comment by rfennell** [comment]
Yes I did mean the  "Microsoft.CSharp", "StyleCop", "StyleCop.Csharp", "StyleCop.Csharp.Rules" DLLs

If you look at my StyleCop extension you will see I distribute these DLLs in the extension, to address exactly the problem you have seen. 

The script assumes the DLLs are in the same folder as the script itself (apart from any addition rule files). But you could change this logic to specify a folder (or default the to standard installation folder)

```

# load the StyleCop classes, this assumes that the StyleCop.DLL, StyleCop.Csharp.DLL,
# StyleCop.Csharp.rules.DLL in the same folder as the StyleCopWrapper.dll

$folder = Split-Path -parent $MyInvocation.MyCommand.Definition  # maybe set this base folder as a parameter?

Write-Verbose ("Loading from folder from [{0}]" -f $folder) 
$dllPath = [System.IO.Path]::Combine($folder,"StyleCopWrapper.dll")
Add-Type -Path $dllPath
$scanner = new-object StyleCopWrapper.Wrapper

```

Does that help?

**Comment by SonizciTR** [comment]
I tried putting everything with powershell script, task.json, image together and uploaded it. It failed same.

We found that if we put every dll name (only the name not full path) in powerhell script with "Add-Type Path" command, everything works.

**Comment by rfennell** [comment]
That work too !

I have found Add-Type a bit 'interesting' to use

**Comment by SonizciTR** [comment]
This happened to be a crazy problem. 

"Add-Type Path" is a workaround for now :) ;) . 

If i find real problem and solve it, i will post.

Thanks for your patience. Thanks again sharing your code.

**Comment by SonizciTR** [comment]
Sorry could not find right solution for this problem. Still using workaround...
