### ISSUE TITLE
Include CommandLine.dll in github releases

### ISSUE THREAD

**Issue by brianpeiris** [rfennell/StyleCopCmdLine#7]
Please include the CommandLine.dll dependency in github releases (preferably in a zip file along with the exe) so that this tool is easier to run immediately

**Comment by rfennell** [comment]
Not a problem, I have updated [v.1.2.0.0 release](https://github.com/rfennell/StyleCopCmdLine/releases/tag/v.1.2.0.0) with the extra DLL

**Comment by brianpeiris** [comment]
Thanks for the quick response!
